### ISSUE TITLE
Building Sign-in and Login Functionality w/ Dedicated Page

### ISSUE THREAD

**Issue by IshmamDC217** [IshmamDC217/BUIT-ChobiGhor#2]
Login Page: We require the development of a dedicated login page that provides a seamless and intuitive interface. It would be ideal to implement a visually appealing and responsive design.

Error Handling: Proper error handling and user feedback mechanisms should be implemented to gracefully handle incorrect login attempts. Clear and informative error messages should be displayed to guide users throughout the process: Perhaps using **_React Toastify_**

Password Security: Maintain standard practices such as password hashing and salting to protect user passwords. Additionally, we need to implement password reset functionality (unless you want us to handle that manually).

Remember Me: We would like to include a "Remember Me" option to allow ourselves to stay logged in across sessions for a convenient user experience.

**Comment by otamam818** [comment]
> Login Page: We require the development of a dedicated login page that provides a seamless and intuitive interface. It would be ideal to implement a visually appealing and responsive design.

Should we perhaps make a login pop-up rather than a login page? It gives us and our parents the advantage of enjoying the homescreen and logging in within the same page. If they don't want to log in, they can just press an "X" button on the pop-up and focus on something else.

On mobile this could perhaps be replaced by a separate overlay page with a dedicated back button.

Here's what it could look like: 
![LoginForm_Overall](https://github.com/IshmamDC217/BUIT-ChobiGhor/assets/68072081/52852c4a-352e-464b-89e5-5ea5fdb3728f)

![LoginForm_DarkAndLight](https://github.com/IshmamDC217/BUIT-ChobiGhor/assets/68072081/533f0e62-218a-46df-b4e3-c9d03c108da0)


> Error Handling: Proper error handling and user feedback mechanisms should be implemented to gracefully handle incorrect login attempts. Clear and informative error messages should be displayed to guide users throughout the process: Perhaps using React Toastify

Implementing error handling is a good opportunity to hone our TypeScript skills. If you want, I can get a working login page implemented with a temporary `.json` file to grab the data from (before we set up the database) and then you can try making it more robust through TypeScript checks and unit tests.

> Password Security: Maintain standard practices such as password hashing and salting to protect user passwords.

I should be able to learn and implement that as I'm working on the login component.

> Additionally, we need to implement password reset functionality (unless you want us to handle that manually).

Since it keeps the website ownership restricted to our family, I would prefer not even needing to do this. Ultimately your choice.

> Remember Me: We would like to include a "Remember Me" option to allow ourselves to stay logged in across sessions for a convenient user experience.

This is doable but is essentially a full-stack task:
- The front-end needs to handle client-side cookies
- The back-end needs to handle user sessions based on cookies within a time period

I reckon this is a problem if it's own and should be handled as a separate issue.
